#############################################################################
# Makefile for building: qArduinoSimulator
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  qArduinoSimulator.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile qArduinoSimulator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iarduino/cores -Iarduino/variants -Iinclude -Iarduino/variants/eightanaloginputs -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qArduinoSimulator1.0.0
DISTDIR = /home/netpipe/Desktop/qArduinoSimulator/.tmp/qArduinoSimulator1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sketch/sketch.cpp \
		arduino/cores/WString.cpp \
		arduino/cores/WMath.cpp \
		arduino/cores/USBCore.cpp \
		arduino/cores/Tone.cpp \
		arduino/cores/Stream.cpp \
		arduino/cores/Print.cpp \
		arduino/cores/new.cpp \
		arduino/cores/main.cpp \
		arduino/cores/IPAddress.cpp \
		arduino/cores/HID.cpp \
		arduino/cores/HardwareSerial.cpp \
		arduino/cores/CDC.cpp \
		arduino/cores/wiring.c \
		arduino/cores/wiring_shift.c \
		arduino/cores/wiring_pulse.c \
		arduino/cores/wiring_digital.c \
		arduino/cores/wiring_analog.c \
		arduino/cores/WInterrupts.c \
		arduino/cores/CDC.cpp \
		arduino/cores/HardwareSerial.cpp \
		arduino/cores/HID.cpp \
		arduino/cores/IPAddress.cpp \
		arduino/cores/main.cpp \
		arduino/cores/new.cpp \
		arduino/cores/Print.cpp \
		arduino/cores/Stream.cpp \
		arduino/cores/Tone.cpp \
		arduino/cores/USBCore.cpp \
		arduino/cores/WMath.cpp \
		arduino/cores/WString.cpp \
		sketch/sketch.cpp \
		main.cpp \
		mainwindow.cpp \
		moc_mainwindow.cpp \
		arduino/cores/WInterrupts.c \
		arduino/cores/wiring.c \
		arduino/cores/wiring_analog.c \
		arduino/cores/wiring_digital.c \
		arduino/cores/wiring_pulse.c \
		arduino/cores/wiring_shift.c moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sketch.o \
		WString.o \
		WMath.o \
		USBCore.o \
		Tone.o \
		Stream.o \
		Print.o \
		new.o \
		main.o \
		IPAddress.o \
		HID.o \
		HardwareSerial.o \
		CDC.o \
		wiring.o \
		wiring_shift.o \
		wiring_pulse.o \
		wiring_digital.o \
		wiring_analog.o \
		WInterrupts.o \
		CDC.o \
		HardwareSerial.o \
		HID.o \
		IPAddress.o \
		main.o \
		new.o \
		Print.o \
		Stream.o \
		Tone.o \
		USBCore.o \
		WMath.o \
		WString.o \
		sketch.o \
		main.o \
		mainwindow.o \
		moc_mainwindow.o \
		WInterrupts.o \
		wiring.o \
		wiring_analog.o \
		wiring_digital.o \
		wiring_pulse.o \
		wiring_shift.o \
		moc_mainwindow.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreQt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreSettingsQt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		qArduinoSimulator.pro mainwindow.h \
		arduino/cores/WString.h \
		arduino/cores/wiring_private.h \
		arduino/cores/WCharacter.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h \
		arduino/cores/USBAPI.h \
		arduino/cores/Udp.h \
		arduino/cores/Stream.h \
		arduino/cores/stdint.h \
		arduino/cores/Server.h \
		arduino/cores/Printable.h \
		arduino/cores/Print.h \
		arduino/cores/Platform.h \
		arduino/cores/new.h \
		arduino/cores/IPAddress.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Client.h \
		arduino/cores/binary.h \
		arduino/cores/ardusim.h \
		arduino/cores/Arduino.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/Client.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/IPAddress.h \
		arduino/cores/new.h \
		arduino/cores/Platform.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/Server.h \
		arduino/cores/stdint.h \
		arduino/cores/Stream.h \
		arduino/cores/Udp.h \
		arduino/cores/USBAPI.h \
		arduino/cores/USBCore.h \
		arduino/cores/USBDesc.h \
		arduino/cores/WCharacter.h \
		arduino/cores/wiring_private.h \
		arduino/cores/WString.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/leonardo/pins_arduino.h \
		arduino/variants/mega/pins_arduino.h \
		arduino/variants/micro/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		include/avr/common.h \
		include/avr/eeprom.h \
		include/avr/fuse.h \
		include/avr/interrupt.h \
		include/avr/io.h \
		include/avr/iom1280.h \
		include/avr/iom168p.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/lock.h \
		include/avr/pgmspace.h \
		include/avr/portpins.h \
		include/avr/sfr_defs.h \
		include/avr/version.h \
		include/avr/wdt.h \
		include/util/atomic.h \
		include/util/crc16.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		include/util/parity.h \
		include/util/setbaud.h \
		include/util/twi.h \
		mainwindow.h \
		moc_predefs.h \
		ui_mainwindow.h main.cpp \
		mainwindow.cpp \
		sketch/sketch.cpp \
		arduino/cores/WString.cpp \
		arduino/cores/WMath.cpp \
		arduino/cores/USBCore.cpp \
		arduino/cores/Tone.cpp \
		arduino/cores/Stream.cpp \
		arduino/cores/Print.cpp \
		arduino/cores/new.cpp \
		arduino/cores/main.cpp \
		arduino/cores/IPAddress.cpp \
		arduino/cores/HID.cpp \
		arduino/cores/HardwareSerial.cpp \
		arduino/cores/CDC.cpp \
		arduino/cores/wiring.c \
		arduino/cores/wiring_shift.c \
		arduino/cores/wiring_pulse.c \
		arduino/cores/wiring_digital.c \
		arduino/cores/wiring_analog.c \
		arduino/cores/WInterrupts.c \
		arduino/cores/CDC.cpp \
		arduino/cores/HardwareSerial.cpp \
		arduino/cores/HID.cpp \
		arduino/cores/IPAddress.cpp \
		arduino/cores/main.cpp \
		arduino/cores/new.cpp \
		arduino/cores/Print.cpp \
		arduino/cores/Stream.cpp \
		arduino/cores/Tone.cpp \
		arduino/cores/USBCore.cpp \
		arduino/cores/WMath.cpp \
		arduino/cores/WString.cpp \
		sketch/sketch.cpp \
		main.cpp \
		mainwindow.cpp \
		moc_mainwindow.cpp \
		arduino/cores/WInterrupts.c \
		arduino/cores/wiring.c \
		arduino/cores/wiring_analog.c \
		arduino/cores/wiring_digital.c \
		arduino/cores/wiring_pulse.c \
		arduino/cores/wiring_shift.c
QMAKE_TARGET  = qArduinoSimulator
DESTDIR       = 
TARGET        = qArduinoSimulator


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qArduinoSimulator.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreQt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreSettingsQt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		qArduinoSimulator.pro \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile qArduinoSimulator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Attica.pri:
/usr/lib64/qt5/mkspecs/modules/qt_BluezQt.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KActivities.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KArchive.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCompletion.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCrash.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDESu.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KHtml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemModels.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJS.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJSApi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNotifications.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KNTLM.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KParts.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPeople.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPlotting.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KPty.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KrossCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KrossUi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KRunner.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KScreen.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWallet.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreQt5.pri:
/usr/lib64/qt5/mkspecs/modules/qt_LibsnoreSettingsQt5.pri:
/usr/lib64/qt5/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib64/qt5/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib64/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Prison.pri:
/usr/lib64/qt5/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib64/qt5/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib64/qt5/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib64/qt5/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
qArduinoSimulator.pro:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qArduinoSimulator.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h arduino/cores/WString.h arduino/cores/wiring_private.h arduino/cores/WCharacter.h arduino/cores/USBDesc.h arduino/cores/USBCore.h arduino/cores/USBAPI.h arduino/cores/Udp.h arduino/cores/Stream.h arduino/cores/stdint.h arduino/cores/Server.h arduino/cores/Printable.h arduino/cores/Print.h arduino/cores/Platform.h arduino/cores/new.h arduino/cores/IPAddress.h arduino/cores/HardwareSerial.h arduino/cores/Client.h arduino/cores/binary.h arduino/cores/ardusim.h arduino/cores/Arduino.h arduino/cores/Arduino.h arduino/cores/ardusim.h arduino/cores/binary.h arduino/cores/Client.h arduino/cores/HardwareSerial.h arduino/cores/IPAddress.h arduino/cores/new.h arduino/cores/Platform.h arduino/cores/Print.h arduino/cores/Printable.h arduino/cores/Server.h arduino/cores/stdint.h arduino/cores/Stream.h arduino/cores/Udp.h arduino/cores/USBAPI.h arduino/cores/USBCore.h arduino/cores/USBDesc.h arduino/cores/WCharacter.h arduino/cores/wiring_private.h arduino/cores/WString.h arduino/variants/eightanaloginputs/pins_arduino.h arduino/variants/leonardo/pins_arduino.h arduino/variants/mega/pins_arduino.h arduino/variants/micro/pins_arduino.h arduino/variants/standard/pins_arduino.h include/avr/common.h include/avr/eeprom.h include/avr/fuse.h include/avr/interrupt.h include/avr/io.h include/avr/iom1280.h include/avr/iom168p.h include/avr/iom2560.h include/avr/iom328p.h include/avr/lock.h include/avr/pgmspace.h include/avr/portpins.h include/avr/sfr_defs.h include/avr/version.h include/avr/wdt.h include/util/atomic.h include/util/crc16.h include/util/delay.h include/util/delay_basic.h include/util/parity.h include/util/setbaud.h include/util/twi.h mainwindow.h moc_predefs.h ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sketch/sketch.cpp arduino/cores/WString.cpp arduino/cores/WMath.cpp arduino/cores/USBCore.cpp arduino/cores/Tone.cpp arduino/cores/Stream.cpp arduino/cores/Print.cpp arduino/cores/new.cpp arduino/cores/main.cpp arduino/cores/IPAddress.cpp arduino/cores/HID.cpp arduino/cores/HardwareSerial.cpp arduino/cores/CDC.cpp arduino/cores/wiring.c arduino/cores/wiring_shift.c arduino/cores/wiring_pulse.c arduino/cores/wiring_digital.c arduino/cores/wiring_analog.c arduino/cores/WInterrupts.c arduino/cores/CDC.cpp arduino/cores/HardwareSerial.cpp arduino/cores/HID.cpp arduino/cores/IPAddress.cpp arduino/cores/main.cpp arduino/cores/new.cpp arduino/cores/Print.cpp arduino/cores/Stream.cpp arduino/cores/Tone.cpp arduino/cores/USBCore.cpp arduino/cores/WMath.cpp arduino/cores/WString.cpp sketch/sketch.cpp main.cpp mainwindow.cpp moc_mainwindow.cpp arduino/cores/WInterrupts.c arduino/cores/wiring.c arduino/cores/wiring_analog.c arduino/cores/wiring_digital.c arduino/cores/wiring_pulse.c arduino/cores/wiring_shift.c $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/netpipe/Desktop/qArduinoSimulator -I/home/netpipe/Desktop/qArduinoSimulator/arduino/cores -I/home/netpipe/Desktop/qArduinoSimulator/arduino/variants -I/home/netpipe/Desktop/qArduinoSimulator/include -I/home/netpipe/Desktop/qArduinoSimulator/arduino/variants/eightanaloginputs -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/netpipe/Desktop/qArduinoSimulator -I/home/netpipe/Desktop/qArduinoSimulator/arduino/cores -I/home/netpipe/Desktop/qArduinoSimulator/arduino/variants -I/home/netpipe/Desktop/qArduinoSimulator/include -I/home/netpipe/Desktop/qArduinoSimulator/arduino/variants/eightanaloginputs -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-suse-linux -I/usr/include/c++/7/backward -I/usr/lib64/gcc/x86_64-suse-linux/7/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/7/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sketch.o: sketch/sketch.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sketch.o sketch/sketch.cpp

WString.o: arduino/cores/WString.cpp arduino/cores/WString.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WString.o arduino/cores/WString.cpp

WMath.o: arduino/cores/WMath.cpp arduino/cores/ardusim.h \
		arduino/cores/stdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WMath.o arduino/cores/WMath.cpp

USBCore.o: arduino/cores/USBCore.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o USBCore.o arduino/cores/USBCore.cpp

Tone.o: arduino/cores/Tone.cpp include/avr/interrupt.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/pgmspace.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tone.o arduino/cores/Tone.cpp

Stream.o: arduino/cores/Stream.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stream.o arduino/cores/Stream.cpp

Print.o: arduino/cores/Print.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Print.o arduino/cores/Print.cpp

new.o: arduino/cores/new.cpp arduino/cores/new.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o new.o arduino/cores/new.cpp

main.o: arduino/cores/main.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o arduino/cores/main.cpp

IPAddress.o: arduino/cores/IPAddress.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/IPAddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IPAddress.o arduino/cores/IPAddress.cpp

HID.o: arduino/cores/HID.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HID.o arduino/cores/HID.cpp

HardwareSerial.o: arduino/cores/HardwareSerial.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/wiring_private.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HardwareSerial.o arduino/cores/HardwareSerial.cpp

CDC.o: arduino/cores/CDC.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h \
		include/avr/wdt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CDC.o arduino/cores/CDC.cpp

wiring.o: arduino/cores/wiring.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring.o arduino/cores/wiring.c

wiring_shift.o: arduino/cores/wiring_shift.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_shift.o arduino/cores/wiring_shift.c

wiring_pulse.o: arduino/cores/wiring_pulse.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_pulse.o arduino/cores/wiring_pulse.c

wiring_digital.o: arduino/cores/wiring_digital.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_digital.o arduino/cores/wiring_digital.c

wiring_analog.o: arduino/cores/wiring_analog.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_analog.o arduino/cores/wiring_analog.c

WInterrupts.o: arduino/cores/WInterrupts.c include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		include/avr/pgmspace.h \
		arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o WInterrupts.o arduino/cores/WInterrupts.c

CDC.o: arduino/cores/CDC.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h \
		include/avr/wdt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CDC.o arduino/cores/CDC.cpp

HardwareSerial.o: arduino/cores/HardwareSerial.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/wiring_private.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HardwareSerial.o arduino/cores/HardwareSerial.cpp

HID.o: arduino/cores/HID.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HID.o arduino/cores/HID.cpp

IPAddress.o: arduino/cores/IPAddress.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/IPAddress.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IPAddress.o arduino/cores/IPAddress.cpp

main.o: arduino/cores/main.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o arduino/cores/main.cpp

new.o: arduino/cores/new.cpp arduino/cores/new.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o new.o arduino/cores/new.cpp

Print.o: arduino/cores/Print.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Print.o arduino/cores/Print.cpp

Stream.o: arduino/cores/Stream.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stream.o arduino/cores/Stream.cpp

Tone.o: arduino/cores/Tone.cpp include/avr/interrupt.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/pgmspace.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tone.o arduino/cores/Tone.cpp

USBCore.o: arduino/cores/USBCore.cpp arduino/cores/Platform.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/eeprom.h \
		arduino/cores/stdint.h \
		include/avr/interrupt.h \
		include/util/delay.h \
		include/util/delay_basic.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h \
		arduino/cores/USBDesc.h \
		arduino/cores/USBCore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o USBCore.o arduino/cores/USBCore.cpp

WMath.o: arduino/cores/WMath.cpp arduino/cores/ardusim.h \
		arduino/cores/stdint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WMath.o arduino/cores/WMath.cpp

WString.o: arduino/cores/WString.cpp arduino/cores/WString.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WString.o arduino/cores/WString.cpp

sketch.o: sketch/sketch.cpp arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sketch.o sketch/sketch.cpp

main.o: main.cpp mainwindow.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

WInterrupts.o: arduino/cores/WInterrupts.c include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		include/avr/pgmspace.h \
		arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o WInterrupts.o arduino/cores/WInterrupts.c

wiring.o: arduino/cores/wiring.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring.o arduino/cores/wiring.c

wiring_analog.o: arduino/cores/wiring_analog.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_analog.o arduino/cores/wiring_analog.c

wiring_digital.o: arduino/cores/wiring_digital.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_digital.o arduino/cores/wiring_digital.c

wiring_pulse.o: arduino/cores/wiring_pulse.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_pulse.o arduino/cores/wiring_pulse.c

wiring_shift.o: arduino/cores/wiring_shift.c arduino/cores/wiring_private.h \
		arduino/cores/Arduino.h \
		arduino/cores/ardusim.h \
		arduino/cores/stdint.h \
		include/avr/pgmspace.h \
		include/avr/io.h \
		include/avr/sfr_defs.h \
		include/avr/iom1280.h \
		include/avr/iom2560.h \
		include/avr/iom328p.h \
		include/avr/iom168p.h \
		include/avr/portpins.h \
		include/avr/common.h \
		include/avr/version.h \
		include/avr/fuse.h \
		include/avr/lock.h \
		include/avr/interrupt.h \
		arduino/cores/binary.h \
		arduino/cores/WCharacter.h \
		arduino/cores/WString.h \
		arduino/cores/HardwareSerial.h \
		arduino/cores/Stream.h \
		arduino/cores/Print.h \
		arduino/cores/Printable.h \
		arduino/cores/new.h \
		arduino/cores/USBAPI.h \
		arduino/variants/eightanaloginputs/pins_arduino.h \
		arduino/variants/standard/pins_arduino.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o wiring_shift.o arduino/cores/wiring_shift.c

moc_mainwindow.o: moc_mainwindow.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

